### ISSUE TITLE
Reorder suites

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#180] opened 2017-10-10 08:13 UTC
Reordering suites could be quite useful. In a similar way you move tabs around browsers or editors

**Comment by rafaelleru** [comment] 2017-10-20 15:23
https://github.com/SortableJS/Vue.Draggable maybe this helps

**Comment by rkomiyama** [comment] 2017-11-02 19:48
I'd like to be assigned for this task.

**Comment by rafaelleru** [comment] 2017-11-02 21:09
I have this almost done😅

**Comment by angrykoala** [comment] 2017-11-02 21:17
oh, well, are you already working on that @rkomiyama ?

**Comment by rkomiyama** [comment] 2017-11-02 21:25
@angrykoala Nope, didn't really get a chance to look into how I was going to work on it. I'll look for something else to work on :)

**Comment by angrykoala** [comment] 2017-11-02 21:29
@rkomiyama Because I'm releasing 0.4 today, I'll spend some time reordering issues for the mileston 0.5 to check priorities, you can look issues there

**Comment by rafaelleru** [comment] 2017-11-04 18:18
Hy
I'm having a little problem. When I try to set up a new selected suite it isn't set correctly and I can figure out why this is happening,k I verified that index works find. Here is the code:
https://github.com/rafaelleru/gaucho/blob/reorder_suites%23180/app/renderer/components/navbar.js#L110

**Comment by angrykoala** [comment] 2017-11-04 23:23
I don't really understand the problem you are having. Are you sure newIndex is correctly defined and it is entering the if?

**Comment by rafaelleru** [comment] 2017-11-05 18:23
Yes, the problem is that the selector must be assigned to the suite in position newIndex but it never is assigned correctly, but logs in console show the corrects indexl

**Comment by angrykoala** [comment] 2017-11-05 19:03
so, the problem is only the selection of the suite after the reordering?

**Comment by rafaelleru** [comment] 2017-11-05 19:20
yes, and I can't figure out what is happening. :cry:

**Comment by angrykoala** [comment] 2017-11-05 19:27
Ok, I'll investigate your branch as soon as I can to see if I can help you

**Comment by rafaelleru** [comment] 2017-11-05 19:43
thanks, I was a little desperate :smiley:

**Comment by angrykoala** [comment] 2017-11-05 20:43
Ok, After testing your version I think the problem (of at least, one of the problems) is that you are not updating the indexes of the tabs when you change the order, so when trying to programatically select a suite it fails.

In fact, by changing: `this.selectTab(evt.newIndex)` to `this.selectTab(evt.oldIndex)` it works (the first time), as it goes to the now changed suite.

It may be a bit tricky, but somehow the indexes should be updated when the tasks are reordered so the logic doesn't break. My guess is that other features work because those are reactive to the actual array, while programmatic selection uses indexes

I recommend you to start the dev version of gaucho (`npm run start-dev`), reorder 2 suites, go clicking to the second suite and write `AppStatus.activeSuite`, you'll see how the active suite is actually the "first one".

**Closed** 2018-06-16 22:17 UTC
Labels: feature
