### ISSUE TITLE
Problem unzipping Mac build for 0.2.4 and 0.2.3

### ISSUE THREAD

**Issue by setegonz** [angrykoala/gaucho#126] opened 2017-08-23 17:47 UTC
Does somebody installed Gaucho 0.2.4 on MacOS Sierra 10.12.6? I'm having issues (both 51.1 MB gaucho-0.2.4-darwin-x64.zip and building from source) but I just want to confirm that it works. Thanks.

**Comment by angrykoala** [comment] 2017-08-23 19:26
Hello @setegonz , sadly, MacOS builds can not be as well tested as other versions, please, could you describe the problem you are having with more detail?

**Comment by setegonz** [comment] 2017-08-23 23:36
![40784494-dfde-468e-a146-3ee00931cb12](https://user-images.githubusercontent.com/11341688/29642947-1d50e01c-8842-11e7-87c1-6eb3dfd71b3e.png)

**Comment by setegonz** [comment] 2017-08-23 23:45
when a try to open the gaucho-0.2.4-darwin-x64.zip version:

![b67b0148-6dcc-479c-b319-9107adb580e4](https://user-images.githubusercontent.com/11341688/29643204-fdc5857a-8843-11e7-8b97-2d7fc18eb322.png)

**Comment by angrykoala** [comment] 2017-08-24 07:51
The first seems like a problem you are having while manually executing the gaucho builder, t omanually execute gaucho try the following steps:
* Download the `master` source code into a folder
* In that folder, execute `npm install` in the terminal
* `npm start` should execute gaucho
* If the following step was working, now you can try `npm run build-electron` to generate the package

> These steps require node and npm installed

The second problem seems a problem extracting the `.zip` file, in fact, I just tried and I had the same problem with the mac build, I'll upload a new file shortly to fix this (and leave a comment here), meanwhile, you can try a local build with the steps above, or gaucho 0.2.3

**Comment by angrykoala** [comment] 2017-08-24 07:55
I'm also having unexpected problems with the build, maybe a dependency problem, so it may take a bit longer to fix

**Comment by setegonz** [comment] 2017-08-24 16:08
@angrykoala I followed all the building steps one by one...And I'm still having the same issue. 


De todas formas me gusta mucho la idea del app. Gracias por compartir!

**Comment by angrykoala** [comment] 2017-08-24 16:24
@setegonz the building problem I was able to reproduce, and I reported as a different issue here #127 , the problem with pre-built files for Mac is a different one, probably a file bad compressed by me. For now, gaucho 0.2.2 should work for mac, while it won't have the latests features, it implements all the core features and you should be able to try it while theses bugs are fixed

**Comment by angrykoala** [comment] 2017-08-24 21:09
According to:
https://github.com/electron-userland/electron-packager/issues/686
and
https://github.com/npm/npm/issues/17781

The build problem seems to happen when using electron-packager with npm@5.3.0, any version below that should work (and probably, it will be fixed in future versions) 

The builds must be done with a different version of npm, to check your npm version execute `npm -v`

**Comment by angrykoala** [comment] 2017-08-24 21:32
Gaucho 0.2.4 re-uploaded, this time with as a `.7z` file, tested to decompress correctly

**Comment by angrykoala** [comment] 2017-08-24 21:34
7z seems to still have issues

**Comment by angrykoala** [comment] 2017-10-31 14:30
This is no longer relevant, due to #43

**Closed by angrykoala** 2017-10-31 14:30 UTC
Labels: bug, critical
